### ISSUE TITLE
Popup-Widget requires localStorage - breaks if 3rd party cookies are blocked

### ISSUE THREAD

**Issue by boldtrn** [meetergo/meetergo-integration#11]
We just added the Popup-Widget to our website. If you have Chrome set with 3rd party cookie blocking and click the book meeting button, the loading spinner is shown and this exception is thrown in the console.

It seems that localStorage is required. Any reason this is actually required?

This is relatively common when working with iFrames. Is it possible to either avoid using localStorage or at least catch the exception?

```
main.e95c8e3159195a0a.js:2 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at u (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:1051761)
    at https://my.meetergo.com/main.e95c8e3159195a0a.js:2:2627451
    at Ps (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4728453)
    at uc (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4748779)
    at https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4747523
    at dc (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4747588)
    at Kl (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4739305)
    at Ti (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4682360)
    at https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4747583
    at dc (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4747588)
rs @ main.e95c8e3159195a0a.js:2
n.callback @ main.e95c8e3159195a0a.js:2
oa @ main.e95c8e3159195a0a.js:2
cl @ main.e95c8e3159195a0a.js:2
ll @ main.e95c8e3159195a0a.js:2
sl @ main.e95c8e3159195a0a.js:2
(anonymous) @ main.e95c8e3159195a0a.js:2
dc @ main.e95c8e3159195a0a.js:2
Kl @ main.e95c8e3159195a0a.js:2
Ti @ main.e95c8e3159195a0a.js:2
(anonymous) @ main.e95c8e3159195a0a.js:2
dc @ main.e95c8e3159195a0a.js:2
Jl @ main.e95c8e3159195a0a.js:2
w @ main.e95c8e3159195a0a.js:2
N @ main.e95c8e3159195a0a.js:2
T.<computed> @ polyfills.0aaa21a89be8fa0f.js:1
M @ polyfills.0aaa21a89be8fa0f.js:1
j @ polyfills.0aaa21a89be8fa0f.js:1
main.e95c8e3159195a0a.js:2 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at u (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:1051761)
    at https://my.meetergo.com/main.e95c8e3159195a0a.js:2:2627451
    at Ps (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4728453)
    at uc (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4748779)
    at https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4747523
    at dc (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4747588)
    at Kl (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4739305)
    at Ti (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4682360)
    at https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4747583
    at dc (https://my.meetergo.com/main.e95c8e3159195a0a.js:2:4747588)
```

**Comment by boy51** [comment]
Should no longer be an issue, if it persists please reopen.
